### ISSUE TITLE
Foreman dependency

### ISSUE THREAD

**Issue by soulim** [interagent/pliny#126]
Hey guys!

Thank you a lot for the awesome project! Could you tell me why foreman gem isn't mentioned in `Gemfile` as a development dependency? Is that your internal convention and foreman is some kind of default tool like bundler? I mean this `Gemfile` https://github.com/interagent/pliny/blob/master/lib/template/Gemfile.

I guess it would be nice to automatically install foreman with other gems when you run `bin/setup`.

**Comment by brandur** [comment]
Hey @soulim! Sorry about the delayed reply here.

> Thank you a lot for the awesome project! Could you tell me why foreman gem isn't mentioned in Gemfile as a development dependency? Is that your internal convention and foreman is some kind of default tool like bundler? I mean this Gemfile https://github.com/interagent/pliny/blob/master/lib/template/Gemfile.

So the the main reason is that the space of process runners is a little up in the air. Foreman was the traditional solution, but since has been largely dropped in favor of [forego](https://github.com/ddollar/forego), and also [dotenv](https://github.com/bkeepers/dotenv) which is a lighter-weight solution preferred by some.

**Comment by soulim** [comment]
Thank you for the explanation @brandur! Going to play with forego as well :smile: 
Will close this issue because you answered on my question on 100%.
